USE GOODSREVIEW;

DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	BEAN_NAME TINYTEXT NOT NULL,
	PARAMS TEXT,
	SCHEDULING_TYPE TINYTEXT NOT NULL,
    SCHEDULING_TIME INT NOT NULL,
    LAST_RUN LONG,
    LAST_PING LONG
);

DROP TABLE IF EXISTS TASK_RESULT;
CREATE TABLE TASK_RESULT(
  	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  	TASK_ID INT
  	STATUS TINYTEXT NOT NULL,
    MESSAGE TEXT NOT NULL
);

ALTER TABLE TASK_RESULT ADD CONSTRAINT FK_TASK_ID
FOREIGN KEY (TASK_ID)
REFERENCES TASK(ID)
ON UPDATE CASCADE ON DELETE RESTRICT;
