use gr_db;

DROP TABLE if EXISTS ENTITY;
CREATE TABLE ENTITY(
	ID INT PRIMARY KEY NOT NULL auto_increment,
	ENTITY_TYPE_ID INT NOT NULL,
	ENTITY_ID INT NOT NULL,
	ENTITY_ATTRS longtext NOT NULL,
	ENTITY_HASH tinytext NOT NULL,
    WATCH_DATE TIMESTAMP NOT NULL
);

DROP TABLE if EXISTS ENTITY_TYPE;
CREATE TABLE ENTITY_TYPE(
    TYPE_ID INT NOT NULL,
    TYPE_NAME text NOT NULL,
    PRIMARY KEY(TYPE_ID)
);


